#!/bin/sh
#
# This software is a part of isar demo.
# Copyright (c) Siemens AG, 2025
#
# SPDX-License-Identifier: MIT

set -e

HOSTNAME="isar-demo"

echo "${HOSTNAME}" > /etc/hostname
echo "127.0.1.1	${HOSTNAME}" >> /etc/hosts
