# This software is a part of isar demo.
# Copyright (c) Siemens AG, 2026
#
# SPDX-License-Identifier: MIT

DISTRO = "debian-trixie"
MACHINE = "x86-pc"

INSTALLER_MC = "demo-installer"
INSTALLER_TARGET_IMAGE = "demo-image-client"
INSTALLER_TARGET_DISTRO = "debian-trixie"
INSTALLER_TARGET_MACHINE = "amd64-swupdate"
