# This software is a part of isar demo.
# Copyright (c) Siemens AG, 2026
#
# SPDX-License-Identifier: MIT

# based on isar/meta-isar/conf/machine/x86-pc.conf
require conf/machine/x86-pc.conf
# based on meta-demo/conf/machine/swupdate-config.inc
require conf/machine/swupdate-config.inc

# set A/B partitioning layout and efibootguard, by using isar-cip-core/wic/x86-uefi-efibootguard.wks.in
WKS_FILE = "x86-uefi-efibootguard.wks.in"
