# This software is a part of isar demo.
# Copyright (c) Siemens AG, 2025
#
# SPDX-License-Identifier: MIT

# based on isar/meta-isar/conf/machine/rpi-arm64-v8-efi.conf
require conf/machine/rpi-arm64-v8-efi.conf
# based on meta-demo/conf/machine/swupdate-config.inc
require conf/machine/swupdate-config.inc

# set A/B partitioning layout and efibootguard, by using meta-demo/scripts/lib/wic/canned-wks/rpi-arm64-v8-ebg.wks.in
WKS_FILE = "rpi-arm64-v8-demo.wks.in"
